### ISSUE TITLE
3702078 - Neilson Creek 

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_peace_2023_reporting#17]
Phase 1 submission

mentions dam in comments but no specifics (dam name, how far upstream, beaver dam?, metal dam?, height etc.).  the dam photo input to mergin is great. by viewing the dam point in the `crossings` layer we can add more detail to the submission. Nothing is more relevant to fish passage than a 1.8m high metal dam, ~30m upstream of the FSR owned by MoE....

![image](https://github.com/NewGraphEnvironment/fish_passage_peace_2023_reporting/assets/46538103/6b5e4ffe-cc17-4ac6-9be4-acfb3ad000c0)

**Comment by Mateo9569** [comment]
Closed via #32
