### ISSUE TITLE
Modelled 2200114 - Whiskers Creek - campground roads

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_peace_2023_reporting#18]
Comments mention - "There are four bridges in total within 200m, with 2 inventoried. Other two bridges should be added to bcfishpass.  "

Can close once complete.

**Comment by Mateo9569** [comment]
Closed via [PR #419](https://github.com/smnorris/bcfishpass/pull/419)
