### ISSUE TITLE
3700002 - Copper Creek

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_peace_2023_reporting#19]
Comments say "Backwatered. No water in culvert. " but those two things together aren't possible. Review of photos indicates pipe is indeed dry. Perched culvert is another reason not backwatered

habitat rated as low value but burbot known upstream and channel width is 3.7m.  Major drought year.  Could prob bump to moderate value due to ponds/lakes/fish upstream and large watershed

Can remove upstream 3701102 from modeling useing csv in `bcfishpass`

Note: we all should now be sure to take separate photos for each input in dff (ex. barrel and outlet) to avoid photo duplicate management issues further down the line

**Comment by Mateo9569** [comment]
There is a photo in the sorted site folder of the barrel, but it's not tagged as `_barrel`. I'm guessing what happened is when I went to add the barrel photo to the mergin form I accidently chose the wrong photo. Should I just change that by hand? I would have to change it in the `2023_data/peace` directory as well as the `PSCIS/phase1_submissions/2023/peace` correct?

**Comment by Mateo9569** [comment]
Fixed in both directories

**Comment by Mateo9569** [comment]
Closed via 24045e5b016c1585d480241f26b116805f0ab08b
