### ISSUE TITLE
3701553 - Miller Creek

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_peace_2023_reporting#21]
- [x] says 80% backwatered but photos do not look that way (could just be a weird angle?)
- [x] outlet photo looks more like downstream should. Need to see the outlet of the pipe so we can see things like outlet drop and backwatering
- [x] 4 modelled crossings upstream can be removed with bcfishpass csv based on review of aerial imager (no road there).  Note that the roadline runs right through huge ponds (not possible - see screenshot)
- [x] should mention in comments there is an unassessed crossing (modelled crossing 3703407) downstream on the railway

![image](https://github.com/NewGraphEnvironment/fish_passage_peace_2023_reporting/assets/46538103/a208cafc-bd12-4cbc-8777-f382e7ea379c)

**Comment by Mateo9569** [comment]
I added to bcfishpass csv. Will close this once I PR.
