### ISSUE TITLE
3702959 - Tributary to Weedon Creek

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_peace_2023_reporting#26]
- [x] photos indicated backwatered while spreadsheet does not
- [x] should make note of beaver cage on inlet
- [ ] outlet photo taken from bad angle
- [x] duplicate photo used for upstream and inlet but there is a better upstream photo in the file (should be fixed in 2023_data and PSCIS/phase1 _submissions/2023.
- [x] road permit holder is Canfor

![image](https://github.com/NewGraphEnvironment/fish_passage_peace_2023_reporting/assets/46538103/63057e58-27fc-41f2-98f4-c1da4b52d2a5)

**Comment by Mateo9569** [comment]
Closed via 24045e5b016c1585d480241f26b116805f0ab08b, and changed photo in onedrive
