### ISSUE TITLE
2200301 - Tributary to Hammett Creek

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_peace_2023_reporting#27]
- [x] road permit holder is Canfor and ff-id = R01860
- [x] special characters in the comments. spent hours troubleshooting problems that arise in report tables before due to this. Nightmare. important to remove
- [x] loaded  gps points and tracks to the QGIS project to review location to see if it is correct (its not - see waypoint). Please adjust and repopulate spreadsheet coordinates

![image](https://github.com/NewGraphEnvironment/fish_passage_peace_2023_reporting/assets/46538103/1a3d86ca-bc5d-47fc-9f3a-52d55cd9566e)

![image](https://github.com/NewGraphEnvironment/fish_passage_peace_2023_reporting/assets/46538103/60f0fe10-f280-4d9f-a07f-165abe3a1d79)

**Comment by Mateo9569** [comment]
Closed via 24045e5b016c1585d480241f26b116805f0ab08b
