### ISSUE TITLE
Watershed stats are missing from `wshds` object

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/fish_passage_peace_2023_reporting#40]
This is due to fpr issue linked [here](https://github.com/NewGraphEnvironment/fpr/issues/44). `wshds` object is built and is in the sqlite db. Watershed areas and site elevations are included but the other watershed stats are missing.

**Comment by NewGraphEnvironment** [comment]
closed here https://github.com/NewGraphEnvironment/fpr/commit/6e35328fa22115709e7665de5507a5968ee45ea4
