### ISSUE TITLE
Add downstream habitat survey site 198714 to trib to McLeod Lake site memo - 198666

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/fish_passage_peace_2023_reporting#41]
Currently there is only culvert and habitat info for the highway crossing. Info on the culvert downstream near the lake should also be added.

**Comment by NewGraphEnvironment** [comment]
closing in favour of https://github.com/NewGraphEnvironment/fish_passage_peace_2023_reporting/issues/54
