### ISSUE TITLE
`form_fiss_site` data import things to note

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/fish_passage_peace_2023_reporting#7]
A few important things to note when we read the fiss data in:

- Upstream and downstream surveys for site 2200799 are NOT in mergin but they are on paper cards. I remember I had an issue getting the fiss site mergin form to show up so I just did a paper card (the problem was I was in the wrong project theme)
- Site data for electrofishing on site 125231 (trib to parsnip) is located in a different project file called `form_fiss_site_20230828`. Make sure to read in all fiss_site files when reading in data. 

Just making a note of this here so we don't forget, will close once all the data is in.

**Comment by Mateo9569** [comment]
Upstream and downstream survey for site 2200799 has now been added to new amalgamated geopackage file in Q (`form_fiss_site_20231027.gpkg`).

**Comment by NewGraphEnvironment** [comment]
restructureing `fiss_site_tidy.R` to do as much cleaning as possible before reburn to gpkg in Q
