### ISSUE TITLE
Bridge site id 3700783 has no span or width

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/fish_passage_peace_2023_reporting#8]
There is no span or width seen on the mergin form or the photo of the paper card. @NewGraphEnvironment did you perhaps take a picture of the site card before you filled that data in? Can you check the site card?

**Comment by NewGraphEnvironment** [comment]
no need to @mention me as i get notifications of all issues as the owner (until I turn them off which hasn't happened yet)

No width or length noted on paper card.  

Not sure why I rushed through recording that. doh

looking at the photos I would estimate 5m x 13m

**Comment by Mateo9569** [comment]
Thanks, changed it in Q and input into template
