### ISSUE TITLE
Culvert 3702446 has no downstream channel width due to lack of defined channel

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/fish_passage_peace_2023_reporting#9]
There is nothing in the methods that talks about this. If there is no sign of any stream channel at all, what should the downstream channel width be? The culvert diameter?

**Comment by NewGraphEnvironment** [comment]
I'd try 0m. I don't think the submission would choke on a 0 but if it did we could do 0.1m or something really tiny. obviously will be in the comments too (sure it is already)

**Comment by Mateo9569** [comment]
Yes it's in the comments, I don't think it will choke
